export default {
  app: {
    name: 'OLm-Mn-wed',
    slogan: 'Local AI Model WebUI',
    backendLabel: 'Model backend',
    hideSidebar: 'Hide sidebar (restore via the ☰ button)',
  },
  nav: {
    chat: 'Chat',
    knowledge: 'Knowledge',
    models: 'Models',
    api: 'API',
    settings: 'Settings',
  },
  common: {
    login: 'Sign in',
    logout: 'Sign out',
    username: 'Username',
    password: 'Password',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    create: 'Create',
    confirm: 'Confirm',
    search: 'Search',
    upload: 'Upload',
    refresh: 'Refresh',
    loading: 'Loading…',
    error: 'Something went wrong',
    success: 'Done',
    empty: 'Nothing here yet',
    comingSoon: 'This feature arrives in a later stage',
    retry: 'Retry',
  },
  theme: {
    title: 'Theme',
    dark: 'Dark',
    light: 'Light',
    system: 'System',
    themeDesc: 'Switch between dark, light or follow the system',
  },
  language: {
    title: '语言 / Language',
    zh: '简体中文',
    en: 'English',
  },
  login: {
    title: 'Sign in',
    usernamePlaceholder: 'Enter username',
    passwordPlaceholder: 'Enter password',
    hint: 'Default account is admin; the random password is printed in the container logs',
    fail: 'Login failed, check username and password',
  },
  settings: {
    title: 'Settings',
    appearance: 'Appearance',
    security: 'Security',
    account: 'Account',
    backend: 'Model backend',
    backendType: 'Backend type',
    backendUrl: 'Backend URL',
    backendEmbed: 'Embedding model',
    backendRestart: 'Restart',
    backendStop: 'Stop',
    backendStart: 'Start',
    backendConfirmTitle: 'Model backend operation',
    backendConfirmMsg: 'Apply this operation to the model backend? Chat may be temporarily unavailable.',
    system: 'System',
    changePassword: 'Change password',
    changePasswordDesc: 'Update the password of the current account',
    oldPassword: 'Current password',
    newPassword: 'New password (min 6 chars)',
    confirmPassword: 'Confirm new password',
    pwMismatch: 'The new passwords do not match',
    pwTooShort: 'The new password must be at least 6 characters',
    pwChanged: '✅ Password changed',
    changeUsername: 'Change username',
    changeUsernameDesc: 'Current username: {name}',
    newUsername: 'New username (2-64 chars, letters/digits/._-)',
    usernameChanged: '✅ Username changed',
    usernameTaken: 'Username already taken',
    checkUpdate: 'Check for updates',
    checkUpdateDesc: 'Compare latest versions of Ollama and this project',
    checkNow: 'Check now',
    current: 'Current',
    latest: 'Latest',
  },
  chat: {
    newConversation: 'New chat',
    conversations: 'Conversations',
    send: 'Send',
    stop: 'Stop',
    model: 'Model',
    modelStatus: 'Model status',
    unloaded: 'unloaded',
    loaded: 'loaded',
    loadHint: 'Model is not loaded; the first reply may take a while',
    temperature: 'Temperature',
    think: 'Thinking mode',
    thinkDesc: 'For reasoning models such as Qwen3 / DeepSeek',
    effort: 'Reasoning effort',
    effortLow: 'Low',
    effortMedium: 'Medium',
    effortHigh: 'High',
    knowledge: 'Knowledge base',
    knowledgeDisabled: 'Knowledge base arrives in stage 5',
    knowledgeNone: 'No knowledge base',
    mcp: 'MCP server',
    webSearch: 'Web search',
    systemPrompt: 'System Prompt',
    systemPromptPlaceholder: 'Set the AI persona and tone…',
    panel: 'Params',
    persona: 'Persona',
    personaNone: 'No persona',
    personaManage: 'Manage personas',
    personaSave: 'Save persona',
    personaSaveHint: 'Save the current prompt to the selected persona',
    personaName: 'Persona name',
    personaPrompt: 'Persona prompt',
    personaNew: 'New persona',
    personaEdit: 'Edit persona',
    personaDeleteConfirm: 'Delete this persona?',
    personaSaved: 'Persona saved',
    personaEmpty: 'No saved personas yet',
    numCtx: 'Context length',
    saveDefault: 'Save as model defaults',
    loadingModel: 'Loading…',
    ctxHint: 'Takes effect after saving as defaults and the model backend restarts',
    regenerate: 'Regenerate',
    copy: 'Copy',
    copied: 'Copied',
    backendDown: 'Model backend unavailable',
    welcomeTitle: 'Start chatting',
    welcomeDesc: 'Pick a model and type a message. Markdown and code highlighting are supported.',
    selectModel: 'Select a model',
    noModels: 'No models available. Import one in the Models page first.',
    inputPlaceholder: 'Type a message. Enter to send, Shift+Enter for a new line',
    streaming: 'Generating…',
    deleteConversation: 'Delete conversation',
    deleteConfirm: 'Delete this conversation and all its messages?',
    emptyConversations: 'No conversations yet. Click the button above to start.',
    ollamaDown: 'Cannot reach the Ollama service',
    thinking: 'Thinking…',
    thinkHint: 'Think',
    backendErrorHint: 'Check that the model service is running and the selected model can be loaded',
  },
  models: {
    uploadModel: 'Upload model',
    installed: 'Installed models',
    localFiles: 'Local GGUF files',
    import: 'Import',
    noInstalled: 'No models installed yet — upload or scan local GGUF files',
    noLocal: 'No .gguf files found in ./models',
    chooseFile: 'Click to choose a .gguf file',
    localFile: 'Local file',
    modelName: 'Model name',
    modelNamePlaceholder: 'Enter a model name (defaults to the file name)',
    configTitle: 'Model configuration',
    estimate: 'Memory / VRAM estimate',
    estimateBtn: 'Estimate',
    estimateHint: 'Run an estimate before saving to see memory needs based on GGUF size and context length',
    weights: 'Weights (GGUF)',
    total: 'Total',
    deleteTitle: 'Delete model',
    deleteConfirm: 'Delete the model from Ollama',
    deleteFileToo: 'Also remove the local GGUF file',
    uploading: 'Uploading…',
    uploadProgress: 'Upload progress: {p}%',
    uploadCancel: 'Cancel upload',
    uploadCancelled: 'Upload cancelled',
    uploadingBig: 'Uploading a large file (may take minutes). Keep this page open: ',
    uploadDone: '✅ File uploaded',
    importing: 'Registering with the model backend and restarting…',
    importRetryHint: 'Import not finished: the file is saved on the server — click Import again in the Local GGUF files list',
    load: 'Load',
    loadingModel: 'Loading model…',
    loadFailed: 'Failed to load model',
    loadDone: 'Model loaded',
    unload: 'Unload',
    unloading: 'Unloading…',
    unloaded: '✅ Model unloaded (memory released)',
    note: 'Note',
  },
  knowledge: {
    dropTitle: 'Drop files here or click to choose',
    dropSub: 'Supports txt / md / pdf — parsed and vectorized on upload',
    indexing: 'Parsing and vectorizing (first run loads the embedding model)…',
    documents: 'Documents',
    chunks: '{n} chunks',
    empty: 'No documents yet. Upload one to start.',
    deleteTitle: 'Delete document',
    deleteConfirm: 'Delete this document and its vector index?',
    embedHint: 'The knowledge base uses an Ollama embedding model. Make sure it is installed:',
  },
  api: {
    service: 'API service',
    enable: 'Enable API service',
    enableDesc: 'When disabled, /v1/* returns 403 immediately',
    endpoint: 'API endpoint',
    endpointDesc: 'OpenAI-compatible, authenticated with an API key',
    copy: 'Copy',
    port: 'API port',
    portDesc: 'Takes effect after a container restart (docker compose restart webapp)',
    portSaved: 'Port saved. Restart the container to apply it.',
    keys: 'API Keys',
    keyNamePlaceholder: 'Enter a key name',
    createKey: 'Create key',
    newKeyHint: 'New key created (copy it now — it will not be shown again):',
    noKeys: 'No API keys yet. Create one to call /v1/chat/completions',
    lastUsed: 'Last used',
    never: 'never',
    disabled: 'disabled',
    deleteTitle: 'Delete API key',
    deleteKeyConfirm: 'Delete this API key? It stops working immediately.',
    examples: 'Examples',
  },
}
