export default {
  app: {
    name: 'OLm-Mn-wed',
    slogan: '本地 AI 模型 WebUI',
    backendLabel: '模型后端',
    hideSidebar: '隐藏导航栏（点左上角 ☰ 恢复）',
  },
  nav: {
    chat: '聊天',
    knowledge: '知识库',
    models: '模型',
    api: 'API',
    settings: '设置',
  },
  common: {
    login: '登录',
    logout: '退出登录',
    username: '用户名',
    password: '密码',
    save: '保存',
    cancel: '取消',
    delete: '删除',
    edit: '编辑',
    create: '创建',
    confirm: '确认',
    search: '搜索',
    upload: '上传',
    refresh: '刷新',
    loading: '加载中…',
    error: '出错了',
    success: '操作成功',
    empty: '暂无数据',
    comingSoon: '该功能将在后续阶段实现',
    retry: '重试',
  },
  theme: {
    title: '主题',
    dark: '深色',
    light: '浅色',
    system: '跟随系统',
    themeDesc: '切换深色 / 浅色 / 跟随系统',
  },
  language: {
    title: '语言 / Language',
    zh: '简体中文',
    en: 'English',
  },
  login: {
    title: '登录',
    usernamePlaceholder: '请输入用户名',
    passwordPlaceholder: '请输入密码',
    hint: '默认账号 admin，首次启动的随机密码见容器日志',
    fail: '登录失败，请检查用户名和密码',
  },
  settings: {
    title: '设置',
    appearance: '外观',
    security: '安全',
    account: '账号',
    backend: '模型后端',
    backendType: '后端类型',
    backendUrl: '后端地址',
    backendEmbed: '嵌入模型',
    backendRestart: '重启',
    backendStop: '停止',
    backendStart: '启动',
    backendConfirmTitle: '模型后端操作',
    backendConfirmMsg: '确定对模型后端执行该操作吗？操作期间聊天可能暂时不可用。',
    system: '系统',
    changePassword: '修改密码',
    changePasswordDesc: '修改当前账号的登录密码',
    oldPassword: '原密码',
    newPassword: '新密码（至少 6 位）',
    confirmPassword: '确认新密码',
    pwMismatch: '两次输入的新密码不一致',
    pwTooShort: '新密码至少 6 位',
    pwChanged: '✅ 密码修改成功',
    changeUsername: '修改用户名',
    changeUsernameDesc: '当前用户名：{name}',
    newUsername: '新用户名（2-64 位字母/数字/._-）',
    usernameChanged: '✅ 用户名修改成功',
    usernameTaken: '用户名已被占用',
    checkUpdate: '检查更新',
    checkUpdateDesc: '对比 Ollama 与本项目的最新版本',
    checkNow: '立即检查',
    current: '当前',
    latest: '最新',
  },
  chat: {
    newConversation: '新建对话',
    conversations: '会话列表',
    send: '发送',
    stop: '停止',
    model: '模型',
    modelStatus: '模型状态',
    unloaded: '未加载',
    loaded: '已加载',
    loadHint: '模型未加载，首次回复可能需要较长时间',
    temperature: '温度',
    think: '思考模式',
    thinkDesc: '适用于 Qwen3 / DeepSeek 等支持思考的模型',
    effort: '思考长度',
    effortLow: '低',
    effortMedium: '中',
    effortHigh: '高',
    knowledge: '知识库',
    knowledgeDisabled: '知识库功能将在阶段五开放',
    knowledgeNone: '不使用知识库',
    mcp: 'MCP 服务器',
    webSearch: '联网搜索',
    systemPrompt: '人格提示词（System Prompt）',
    systemPromptPlaceholder: '设定 AI 的角色与回答风格…',
    panel: '参数',
    persona: '人格',
    personaNone: '不使用人格',
    personaManage: '管理人格',
    personaSave: '保存人格',
    personaSaveHint: '将当前提示词保存到所选人格',
    personaName: '人格名称',
    personaPrompt: '人格提示词',
    personaNew: '新建人格',
    personaEdit: '编辑人格',
    personaDeleteConfirm: '确定删除该人格吗？',
    personaSaved: '人格已保存',
    personaEmpty: '暂无保存的人格',
    numCtx: '上下文长度',
    saveDefault: '保存为模型默认参数',
    loadingModel: '加载中…',
    ctxHint: '调整后点「保存为模型默认参数」并在模型后端重启后生效',
    regenerate: '重新生成',
    copy: '复制',
    copied: '已复制',
    backendDown: '模型后端不可用',
    welcomeTitle: '开始对话',
    welcomeDesc: '选择模型，输入消息开始聊天。支持 Markdown 渲染与代码高亮。',
    selectModel: '请选择模型',
    noModels: '暂无可用模型，请先到「模型」页导入',
    inputPlaceholder: '输入消息，Enter 发送，Shift+Enter 换行',
    streaming: '正在生成…',
    deleteConversation: '删除会话',
    deleteConfirm: '确定删除该会话及其全部消息吗？',
    emptyConversations: '暂无会话，点击上方按钮新建',
    ollamaDown: '无法连接 Ollama 服务',
    thinking: '思考中…',
    thinkHint: '思考',
    backendErrorHint: '请确认模型服务已启动，且所选模型能够成功加载',
  },
  models: {
    uploadModel: '上传模型',
    installed: '已安装模型',
    localFiles: '本地 GGUF 文件',
    import: '导入',
    noInstalled: '暂无已安装模型，请上传或扫描本地 GGUF 文件',
    noLocal: '未在 ./models 目录发现 .gguf 文件',
    chooseFile: '点击选择 .gguf 文件',
    localFile: '本地文件',
    modelName: '模型名称',
    modelNamePlaceholder: '输入模型名称（默认取文件名）',
    configTitle: '模型配置',
    estimate: '内存 / 显存占用预估',
    estimateBtn: '开始预估',
    estimateHint: '保存配置前可先运行预估，根据 GGUF 大小与上下文长度估算内存需求',
    weights: '权重（GGUF）',
    total: '合计',
    deleteTitle: '删除模型',
    deleteConfirm: '确定从 Ollama 删除模型',
    deleteFileToo: '同时删除本地 GGUF 文件',
    uploading: '正在上传…',
    uploadProgress: '上传进度：{p}%',
    uploadCancel: '取消上传',
    uploadCancelled: '上传已取消',
    uploadingBig: '正在上传大文件（可能需要几分钟），请勿关闭页面：',
    uploadDone: '✅ 文件上传完成',
    importing: '正在注册到模型后端并重启…',
    importRetryHint: '导入未完成：文件已保存在服务器，可到下方「本地 GGUF 文件」列表中重新点击导入',
    load: '加载',
    loadingModel: '正在加载模型…',
    loadFailed: '模型加载失败',
    loadDone: '模型已加载',
    unload: '卸下',
    unloading: '卸下中…',
    unloaded: '✅ 模型已卸下（已释放内存）',
    note: '提示',
  },
  knowledge: {
    dropTitle: '拖拽文件到此处，或点击选择',
    dropSub: '支持 txt / md / pdf，上传后自动解析并向量化',
    indexing: '正在解析与向量化（首次需加载嵌入模型）…',
    documents: '文档',
    chunks: '{n} 个分块',
    empty: '暂无文档，先上传一个吧',
    deleteTitle: '删除文档',
    deleteConfirm: '确定删除该文档及其向量索引吗？',
    embedHint: '知识库使用 Ollama 嵌入模型，请先确保已安装：',
  },
  api: {
    service: 'API 服务',
    enable: '启用 API 服务',
    enableDesc: '关闭后 /v1/* 接口立即返回 403',
    endpoint: 'API 地址',
    endpointDesc: 'OpenAI 兼容接口，使用 API Key 鉴权',
    copy: '复制',
    port: 'API 端口',
    portDesc: '修改后需重启容器生效（docker compose restart webapp）',
    portSaved: '端口已保存，重启容器后生效',
    keys: 'API Keys',
    keyNamePlaceholder: '输入 Key 名称',
    createKey: '创建 Key',
    newKeyHint: '新 Key 已创建（请立即复制保存，之后不再显示）：',
    noKeys: '暂无 API Key，创建一个以调用 /v1/chat/completions',
    lastUsed: '最后使用',
    never: '从未',
    disabled: '已禁用',
    deleteTitle: '删除 API Key',
    deleteKeyConfirm: '确定删除该 API Key 吗？删除后立即失效。',
    examples: '使用示例',
  },
}
